# Generated by Django 4.0.4 on 2022-05-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ud', '0004_alter_notice_notice_alter_pyqs_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice',
            field=models.FileField(blank=True, upload_to='notice'),
        ),
        migrations.AlterField(
            model_name='pyqs',
            name='question',
            field=models.FileField(blank=True, upload_to='pyqs'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(upload_to='resume'),
        ),
    ]
