# Generated by Django 4.0.4 on 2022-05-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ud', '0005_alter_notice_notice_alter_pyqs_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyqs',
            name='question',
            field=models.FileField(blank=True, upload_to='media/pyqs'),
        ),
    ]
