# Generated by Django 4.0.4 on 2022-05-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ud', '0007_alter_pyqs_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice',
            field=models.FileField(blank=True, upload_to='resume'),
        ),
    ]
